# Generated by Django 4.2.6 on 2024-07-15 08:51

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParkingSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("rate", models.IntegerField()),
                ("occupied", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("plate_no", models.CharField(max_length=10)),
                ("token", models.CharField(default=uuid.uuid4, max_length=100)),
                ("checkin_time", models.DateTimeField(auto_now=True)),
                ("checkout_time", models.DateTimeField()),
                (
                    "parkingspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Parking.parkingspace",
                    ),
                ),
            ],
        ),
    ]
