# Generated by Django 4.2.6 on 2024-07-15 09:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Parking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle_info",
            name="checkin_time",
        ),
        migrations.RemoveField(
            model_name="vehicle_info",
            name="checkout_time",
        ),
        migrations.RemoveField(
            model_name="vehicle_info",
            name="parkingspace",
        ),
        migrations.RemoveField(
            model_name="vehicle_info",
            name="token",
        ),
        migrations.CreateModel(
            name="ParkingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(default=uuid.uuid4, max_length=100)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("checkin_time", models.DateTimeField(auto_now=True)),
                ("checkout_time", models.DateTimeField()),
                (
                    "parking_space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Parking.parkingspace",
                    ),
                ),
                (
                    "vehicle_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Parking.vehicle_info",
                    ),
                ),
            ],
        ),
    ]
