# Generated by Django 4.2.6 on 2024-07-16 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0003_alter_parkingdetails_checkin_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdetails',
            name='checkin_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 16, 9, 18, 26, 873141, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='parkingdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 9, 18, 26, 873141, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
