# Generated by Django 4.2.6 on 2024-07-16 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Parking", "0004_alter_parkingdetails_checkin_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingdetails",
            name="checkin_time",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parkingdetails",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
