# Generated by Django 5.0.7 on 2024-07-22 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0006_vehicle_info_parked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdetails',
            name='checkin_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
