# Generated by Django 5.0.7 on 2024-07-17 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("REST_API", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle_info",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="parkingdetails",
            name="vehicle_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="REST_API.vehicle_info"
            ),
        ),
    ]
