# Generated by Django 5.0.7 on 2024-07-18 04:23

import authUser.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authUser.models.CustomUserManager()),
            ],
        ),
    ]
