# Generated by Django 5.0.7 on 2024-07-18 04:23

from django.db import migrations

import authUser.models


class Migration(migrations.Migration):

    dependencies = [
        ("authUser", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", authUser.models.CustomUserManager()),
            ],
        ),
    ]
